---
- name: 'Configuration: Render config directories'
  file:
    path: "{{ nginx_settings_path + '/conf.d/' + item.dst | dirname }}"
    state: directory
    recurse: true
  with_items: '{{ nginx_configuration_files }}'

- name: 'Configuration: Render config files'
  template:
    src: '{{ item.src }}'
    dest: '{{ nginx_settings_path }}/conf.d/{{ item.dst }}'
  with_items: '{{ nginx_configuration_files }}'
  register: nginx_config_files_status
  notify:
    - Restart nginx
