---
- name: 'Configuration: Render mounted directories'
  file:
    path: "{{ item.src | dirname }}"
    state: directory
    recurse: true
  with_items: '{{ nginx_mounted_folders }}'
  register: nginx_mounted_folders_status
