---
- name: 'Configuration: Prepare empty volumes list'
  set_fact:
    nginx_container_volumes: []
  changed_when: false

- name: 'Configuration: Prepare config files volumes list'
  set_fact:
    nginx_container_volumes: "{{ nginx_container_volumes + [ nginx_settings_path + '/configs/' + item.dst + ':/etc/nginx/' + item.dst + ':' + item.mode|default('ro')  ] }}"
  with_items: '{{ nginx_configuration_files }}'
  changed_when: nginx_config_files_status.changed

- name: 'Configuration: Prepare other files volumes list'
  set_fact:
    nginx_container_volumes: "{{ nginx_container_volumes + [ nginx_settings_path + '/other/' + item.dst + ':' + item.dst + ':' + item.mode|default('ro')  ] }}"
  with_items: '{{ nginx_other_files }}'
  changed_when: nginx_other_files_status.changed